name: needs
description: To help you...
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.2
#  firebase_auth: 0.15.5+3
#  cloud_firestore: 0.13.4+2
#  firebase_core: 0.4.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf


